insert into game (name, console, personal_code) values ('Dante`s inferno','PS3','BLUS30405');
insert into game (name, console, personal_code) values ('God of War Colletion','PS3','BCUS9829');
insert into game (name, console, personal_code) values ('Sport Champions','PS3','BCUS98262');
insert into game (name, console, personal_code) values ('Pro Evolution Soccer 2011','PS3','BLUS30610L');
insert into game (name, console, personal_code) values ('Mortal Kombat','PS3','BLUS30522');
insert into game (name, console, personal_code) values ('Call of Duty Black Ops','PS3','BLUS90162');
insert into game (name, console, personal_code) values ('Homefront the Revolution','PS4','2101507');
insert into game (name, console, personal_code) values ('Dying by Light','PS4','2101162');
insert into game (name, console, personal_code) values ('Call of Duty Infinite Warfare','PS4','2102311');
insert into game (name, console, personal_code) values ('Dinasty Warriors 8 Empires','PS4','CUSA01632');
insert into game (name, console, personal_code) values ('Payday 2 Crimewave Edition','PS4','CUSA01770SA');
insert into game (name, console, personal_code) values ('Fifa 12','PS3','BLUS30809SA');
insert into game (name, console, personal_code) values ('Heavy Rain','PS3','BCUS98280');
insert into game (name, console, personal_code) values ('The Elder Scrolls V Skyrim Legendary Edition','PS3','BLUS31202S');
insert into game (name, console, personal_code) values ('Resident Evil 6','PS3','BLUS30855S');
insert into game (name, console, personal_code) values ('Ace Combat Assault Horizon','PS3','BLUS30809SA');
insert into game (name, console, personal_code) values ('Battlefield 3','PS3','BLUS30762SA');
insert into game (name, console, personal_code) values ('Dark Souls','PS3','BLUS30782');
insert into game (name, console, personal_code) values ('Battlefield 1','PS4','2102131');
insert into game (name, console, personal_code) values ('Resident Evil 3','PS4','2105943');
insert into game (name, console, personal_code) values ('Dinasty Warriors Strikeforce','PS3','BLUS30471');
insert into game (name, console, personal_code) values ('Prince of Persia Trilogy','PS3','BLUS30754');
insert into game (name, console, personal_code) values ('Assassin´s Creed Ezio Trilogy','PS3','BLUS31145L');
insert into game (name, console, personal_code) values ('Metal Gear Solid the Phoanthom Pain','PS4','3001338');
insert into game (name, console, personal_code) values ('Pro Evolution Soccer 2018','PS4','3002333');
insert into game (name, console, personal_code) values ('Pro Evolution Soccer 2017','PS4','3001929');
insert into game (name, console, personal_code) values ('Assassin´s Creed','PS3','BLUS30089GH');
insert into game (name, console, personal_code) values ('Dead Space 2','PS3','BLUS30717GH');
insert into game (name, console, personal_code) values ('Uncharted 4 - A Thiefs End','PS4','3000188');
insert into game (name, console, personal_code) values ('Killzone Trilogy','PS3','BCUS99075');
insert into game (name, console, personal_code) values ('Call of Duty Black Ops 2','PS3','BLUS31141');
insert into game (name, console, personal_code) values ('Lego Marvel Super Heroes','PS3','BLUS90162');
insert into game (name, console, personal_code) values ('The Last Of Us','PS3','BCUS98174');
insert into game (name, console, personal_code) values ('Assassin´s Creed IV - Black Flag','PS3','BLUS31193SESA');
insert into game (name, console, personal_code) values ('Call of Duty World at War','PS3','BLUS30192');
insert into game (name, console, personal_code) values ('Twisted Metal','PS3','BCUS98106');
insert into game (name, console, personal_code) values ('Demon´s Souls','PS3','20211694');
insert into game (name, console, personal_code) values ('Midnight Club Los Angeles Complete Edition','PS3','BLUS30442');
insert into game (name, console, personal_code) values ('Grand Theft Auto IV','PS3','BLUS30127GH');